"""
Test Weather Module Adapter

Fetches weather data from Open-Meteo API

Auto-generated by NEXUS Executor Agent.
"""
import httpx
from datetime import datetime
from typing import Dict, Any, List

from shared.adapters.base import BaseAdapter, AdapterConfig
from shared.adapters.registry import register_adapter


API_BASE_URL = "https://api.open-meteo.com/v1/forecast"


@register_adapter(
    category="weather",
    platform="open-meteo",
    display_name="Test Weather Module",
    description="Fetches weather data from Open-Meteo API",
    icon="weather",
    requires_auth=False,
    auth_type="none",
)
class OpenMeteoAdapter(BaseAdapter[Dict[str, Any]]):
    """
    Test Weather Module adapter.
    Fetches data from https://api.open-meteo.com/v1/forecast and transforms to canonical format.
    """

    category = "weather"
    platform = "open-meteo"

    def __init__(self, config: AdapterConfig = None):
        super().__init__(config)
        self._api_base = API_BASE_URL
        self._timeout = httpx.Timeout(30.0)

    async def fetch_raw(self, config: AdapterConfig) -> Dict[str, Any]:
        """Fetch raw data from the Test Weather Module API."""
        headers = {}
        if config and config.credentials:
            api_key = config.credentials.get("api_key", "")
            if api_key:
                headers["Authorization"] = f"Bearer {api_key}"

        async with httpx.AsyncClient(timeout=self._timeout) as client:
            response = await client.get(
                f"{self._api_base}/",
                headers=headers,
            )
            response.raise_for_status()
            return response.json()

    def transform(self, raw_data: Dict[str, Any]) -> List[Dict[str, Any]]:
        """Transform raw API response to canonical format."""
        items = raw_data.get("items", raw_data.get("data", []))
        if not isinstance(items, list):
            items = [items] if items else []

        results = []
        for item in items:
            results.append({
                "id": str(item.get("id", "")),
                "name": str(item.get("name", "")),
                "data": item,
                "fetched_at": datetime.utcnow().isoformat(),
                "platform": self.platform,
            })
        return results

    def get_capabilities(self) -> Dict[str, bool]:
        return {
            "read": True,
            "write": False,
            "real_time": False,
            "batch": True,
            "webhooks": False,
        }
