"""
Tests for Open-MeteoAdapter adapter.

Auto-generated by NEXUS Executor Agent.
Validates adapter contract compliance: fetch_raw, transform, capabilities.
"""
import asyncio
import json
import pytest
from unittest.mock import AsyncMock, patch, MagicMock


def test_adapter_import():
    """Verify the adapter module can be imported."""
    from adapter import Open-MeteoAdapter
    assert Open-MeteoAdapter is not None


def test_adapter_instantiation():
    """Verify the adapter can be instantiated."""
    from adapter import Open-MeteoAdapter
    adapter = Open-MeteoAdapter()
    assert adapter.category == "weather"
    assert adapter.platform == "open-meteo"


def test_adapter_capabilities():
    """Verify capabilities dict has required keys."""
    from adapter import Open-MeteoAdapter
    adapter = Open-MeteoAdapter()
    caps = adapter.get_capabilities()
    assert isinstance(caps, dict)
    assert "read" in caps
    assert "write" in caps


def test_adapter_has_required_methods():
    """Verify adapter implements BaseAdapter interface."""
    from adapter import Open-MeteoAdapter
    adapter = Open-MeteoAdapter()
    assert hasattr(adapter, "fetch_raw")
    assert hasattr(adapter, "transform")
    assert hasattr(adapter, "get_capabilities")
    assert callable(adapter.fetch_raw)
    assert callable(adapter.transform)


def test_adapter_transform_empty():
    """Verify transform handles empty data gracefully."""
    from adapter import Open-MeteoAdapter
    adapter = Open-MeteoAdapter()
    result = adapter.transform({"items": []})
    assert isinstance(result, list)
    assert len(result) == 0


def test_adapter_transform_mock_data():
    """Verify transform processes mock response correctly."""
    from adapter import Open-MeteoAdapter
    adapter = Open-MeteoAdapter()
    mock_data = {"items": [{"id": "1", "name": "test_item", "value": 42}]}
    result = adapter.transform(mock_data)
    assert isinstance(result, list)
    assert len(result) > 0


def test_adapter_fetch_mock():
    """Verify fetch_raw makes correct API call (mocked)."""
    from adapter import Open-MeteoAdapter
    from shared.adapters.base import AdapterConfig

    adapter = Open-MeteoAdapter()
    config = adapter.config

    # Mock httpx response
    mock_response = MagicMock()
    mock_response.json.return_value = {"items": [{"id": "1", "name": "test_item", "value": 42}]}
    mock_response.raise_for_status = MagicMock()

    with patch("httpx.AsyncClient") as mock_client:
        mock_instance = AsyncMock()
        mock_instance.get.return_value = mock_response
        mock_instance.__aenter__ = AsyncMock(return_value=mock_instance)
        mock_instance.__aexit__ = AsyncMock(return_value=False)
        mock_client.return_value = mock_instance

        result = asyncio.get_event_loop().run_until_complete(
            adapter.fetch_raw(config)
        )
        assert isinstance(result, dict)
