# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: tool.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'tool.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import struct_pb2 as google_dot_protobuf_dot_struct__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\ntool.proto\x12\x04tool\x1a\x1cgoogle/protobuf/struct.proto\">\n\x0fWebSearchResult\x12\r\n\x05title\x18\x01 \x01(\t\x12\x0b\n\x03url\x18\x02 \x01(\t\x12\x0f\n\x07snippet\x18\x03 \x01(\t\"I\n\x0bToolRequest\x12\x11\n\ttool_name\x18\x01 \x01(\t\x12\'\n\x06params\x18\x02 \x01(\x0b\x32\x17.google.protobuf.Struct\"\xbd\x01\n\x0cToolResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\x12&\n\x07results\x18\x03 \x03(\x0b\x32\x15.tool.WebSearchResult\x12\x32\n\x08metadata\x18\x04 \x03(\x0b\x32 .tool.ToolResponse.MetadataEntry\x1a/\n\rMetadataEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\x32@\n\x0bToolService\x12\x31\n\x08\x43\x61llTool\x12\x11.tool.ToolRequest\x1a\x12.tool.ToolResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'tool_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_TOOLRESPONSE_METADATAENTRY']._loaded_options = None
  _globals['_TOOLRESPONSE_METADATAENTRY']._serialized_options = b'8\001'
  _globals['_WEBSEARCHRESULT']._serialized_start=50
  _globals['_WEBSEARCHRESULT']._serialized_end=112
  _globals['_TOOLREQUEST']._serialized_start=114
  _globals['_TOOLREQUEST']._serialized_end=187
  _globals['_TOOLRESPONSE']._serialized_start=190
  _globals['_TOOLRESPONSE']._serialized_end=379
  _globals['_TOOLRESPONSE_METADATAENTRY']._serialized_start=332
  _globals['_TOOLRESPONSE_METADATAENTRY']._serialized_end=379
  _globals['_TOOLSERVICE']._serialized_start=381
  _globals['_TOOLSERVICE']._serialized_end=445
# @@protoc_insertion_point(module_scope)
