# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import tool_pb2 as tool__pb2


class ToolServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CallTool = channel.unary_unary(
                '/tool.ToolService/CallTool',
                request_serializer=tool__pb2.ToolRequest.SerializeToString,
                response_deserializer=tool__pb2.ToolResponse.FromString,
                )


class ToolServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def CallTool(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ToolServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CallTool': grpc.unary_unary_rpc_method_handler(
                    servicer.CallTool,
                    request_deserializer=tool__pb2.ToolRequest.FromString,
                    response_serializer=tool__pb2.ToolResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'tool.ToolService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class ToolService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def CallTool(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/tool.ToolService/CallTool',
            tool__pb2.ToolRequest.SerializeToString,
            tool__pb2.ToolResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
