"""
srccheck Adapter

A test module for API calls to https://api.example.com/data.

Auto-generated by NEXUS Executor Agent.
"""
import httpx
from datetime import datetime
from typing import Dict, Any, List

from shared.adapters.base import BaseAdapter, AdapterConfig
from shared.adapters.registry import register_adapter


API_BASE_URL = "https://api.example.com/data"


@register_adapter(
    category="test",
    platform="srccheck",
    display_name="srccheck",
    description="A test module for API calls to https://api.example.com/data.",
    icon="srccheck",
    requires_auth=True,
    auth_type="Bearer",
)
class SrccheckAdapter(BaseAdapter[Dict[str, Any]]):
    """
    srccheck adapter.
    Fetches data from https://api.example.com/data and transforms to canonical format.
    """

    category = "test"
    platform = "srccheck"

    def __init__(self, config: AdapterConfig = None):
        super().__init__(config)
        self._api_base = API_BASE_URL
        self._timeout = httpx.Timeout(30.0)

    async def fetch_raw(self, config: AdapterConfig) -> Dict[str, Any]:
        """Fetch raw data from the srccheck API."""
        headers = {{}}
        if config and config.credentials:
            api_key = config.credentials.get("api_key", "")
            if api_key:
                headers["Authorization"] = f"Bearer {{api_key}}"

        async with httpx.AsyncClient(timeout=self._timeout) as client:
            response = await client.get(
                f"{{self._api_base}}/",
                headers=headers,
            )
            response.raise_for_status()
            return response.json()

    def transform(self, raw_data: Dict[str, Any]) -> List[Dict[str, Any]]:
        """Transform raw API response to canonical format."""
        items = raw_data.get("items", raw_data.get("data", []))
        if not isinstance(items, list):
            items = [items] if items else []

        results = []
        for item in items:
            results.append({{
                "id": str(item.get("id", "")),
                "name": str(item.get("name", "")),
                "data": item,
                "fetched_at": datetime.utcnow().isoformat(),
                "platform": self.platform,
            }})
        return results

    def get_capabilities(self) -> Dict[str, bool]:
        return {
            "read": True,
            "write": False,
            "real_time": False,
            "batch": True,
            "webhooks": False,
        }
