"""
Test Code Generation Template.

Generates pytest tests for a dynamically created adapter module.
Tests verify: import, instantiation, capabilities, fetch, transform.

Template variables:
    {class_name}     - e.g., "ClashRoyaleAdapter"
    {module_name}    - e.g., "clashroyale"
    {category}       - e.g., "gaming"
    {platform}       - e.g., "clashroyale"
    {requires_auth}  - True or False
    {api_base_url}   - e.g., "https://api.clashroyale.com/v1"
    {mock_response}  - JSON string for mock API response
"""

TEST_TEMPLATE = '''"""
Tests for {class_name} adapter.

Auto-generated by NEXUS Executor Agent.
Validates adapter contract compliance: fetch_raw, transform, capabilities.
"""
import asyncio
import json
import pytest
from unittest.mock import AsyncMock, patch, MagicMock


def test_adapter_import():
    """Verify the adapter module can be imported."""
    from adapter import {class_name}
    assert {class_name} is not None


def test_adapter_instantiation():
    """Verify the adapter can be instantiated."""
    from adapter import {class_name}
    adapter = {class_name}()
    assert adapter.category == "{category}"
    assert adapter.platform == "{platform}"


def test_adapter_capabilities():
    """Verify capabilities dict has required keys."""
    from adapter import {class_name}
    adapter = {class_name}()
    caps = adapter.get_capabilities()
    assert isinstance(caps, dict)
    assert "read" in caps
    assert "write" in caps


def test_adapter_has_required_methods():
    """Verify adapter implements BaseAdapter interface."""
    from adapter import {class_name}
    adapter = {class_name}()
    assert hasattr(adapter, "fetch_raw")
    assert hasattr(adapter, "transform")
    assert hasattr(adapter, "get_capabilities")
    assert callable(adapter.fetch_raw)
    assert callable(adapter.transform)


def test_adapter_transform_empty():
    """Verify transform handles empty data gracefully."""
    from adapter import {class_name}
    adapter = {class_name}()
    result = adapter.transform({{"items": []}})
    assert isinstance(result, list)
    assert len(result) == 0


def test_adapter_transform_mock_data():
    """Verify transform processes mock response correctly."""
    from adapter import {class_name}
    adapter = {class_name}()
    mock_data = {mock_response}
    result = adapter.transform(mock_data)
    assert isinstance(result, list)
    assert len(result) > 0


def test_adapter_fetch_mock():
    """Verify fetch_raw makes correct API call (mocked)."""
    from adapter import {class_name}
    from shared.adapters.base import AdapterConfig

    adapter = {class_name}()
    config = adapter.config

    # Mock httpx response
    mock_response = MagicMock()
    mock_response.json.return_value = {mock_response}
    mock_response.raise_for_status = MagicMock()

    with patch("httpx.AsyncClient") as mock_client:
        mock_instance = AsyncMock()
        mock_instance.get.return_value = mock_response
        mock_instance.__aenter__ = AsyncMock(return_value=mock_instance)
        mock_instance.__aexit__ = AsyncMock(return_value=False)
        mock_client.return_value = mock_instance

        result = asyncio.get_event_loop().run_until_complete(
            adapter.fetch_raw(config)
        )
        assert isinstance(result, dict)
'''

DEFAULT_MOCK_RESPONSE = '{"items": [{"id": "1", "name": "test_item", "value": 42}]}'


def generate_test_code(
    class_name: str,
    module_name: str,
    category: str,
    platform: str,
    requires_auth: bool = True,
    api_base_url: str = "https://api.example.com/v1",
    mock_response: str = "",
) -> str:
    """Generate pytest test code for an adapter module."""
    if not mock_response:
        mock_response = DEFAULT_MOCK_RESPONSE

    return TEST_TEMPLATE.format(
        class_name=class_name,
        module_name=module_name,
        category=category,
        platform=platform,
        requires_auth=requires_auth,
        api_base_url=api_base_url,
        mock_response=mock_response,
    )
